
services:
  - type: web
    name: web2appify-backend
    env: docker
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
